services:
  http-backend:
    build:
      context: .
      dockerfile: dockerfile/dockerfile.httpbackend 
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3001
    ports:
      - "3001:3001"
  
  ws-backend:
    build:
      context: .
      dockerfile: dockerfile/dockerfile.wsbackend 
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3002
    ports:
      - "3002:3002"

  web:
    build:
      context: .
      dockerfile: dockerfile/dockerfile.frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
    ports:
      - "3000:3000"
    depends_on:
      - http-backend
      - ws-backend